//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 13 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `c000000`.
    var c000000: RswiftResources.ColorResource { .init(name: "c000000", path: [], bundle: bundle) }

    /// Color `c007AFF`.
    var c007AFF: RswiftResources.ColorResource { .init(name: "c007AFF", path: [], bundle: bundle) }

    /// Color `c00C7BE`.
    var c00C7BE: RswiftResources.ColorResource { .init(name: "c00C7BE", path: [], bundle: bundle) }

    /// Color `c62B6B6`.
    var c62B6B6: RswiftResources.ColorResource { .init(name: "c62B6B6", path: [], bundle: bundle) }

    /// Color `c686868`.
    var c686868: RswiftResources.ColorResource { .init(name: "c686868", path: [], bundle: bundle) }

    /// Color `c949494`.
    var c949494: RswiftResources.ColorResource { .init(name: "c949494", path: [], bundle: bundle) }

    /// Color `c98989D`.
    var c98989D: RswiftResources.ColorResource { .init(name: "c98989D", path: [], bundle: bundle) }

    /// Color `cC8C7CC`.
    var cC8C7CC: RswiftResources.ColorResource { .init(name: "cC8C7CC", path: [], bundle: bundle) }

    /// Color `cF2F2F2`.
    var cF2F2F2: RswiftResources.ColorResource { .init(name: "cF2F2F2", path: [], bundle: bundle) }

    /// Color `cF8F8F8`.
    var cF8F8F8: RswiftResources.ColorResource { .init(name: "cF8F8F8", path: [], bundle: bundle) }

    /// Color `cFEFFFF`.
    var cFEFFFF: RswiftResources.ColorResource { .init(name: "cFEFFFF", path: [], bundle: bundle) }

    /// Color `cFF2600`.
    var cFF2600: RswiftResources.ColorResource { .init(name: "cFF2600", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 35 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `adBanner1`.
    var adBanner1: RswiftResources.ImageResource { .init(name: "adBanner1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `adBanner2`.
    var adBanner2: RswiftResources.ImageResource { .init(name: "adBanner2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `adBanner3`.
    var adBanner3: RswiftResources.ImageResource { .init(name: "adBanner3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backButtonImage`.
    var backButtonImage: RswiftResources.ImageResource { .init(name: "backButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `catalogTabBarIcon`.
    var catalogTabBarIcon: RswiftResources.ImageResource { .init(name: "catalogTabBarIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gradient`.
    var gradient: RswiftResources.ImageResource { .init(name: "gradient", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mapPin`.
    var mapPin: RswiftResources.ImageResource { .init(name: "mapPin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mapPinSelected`.
    var mapPinSelected: RswiftResources.ImageResource { .init(name: "mapPinSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mapTapBarIcon`.
    var mapTapBarIcon: RswiftResources.ImageResource { .init(name: "mapTapBarIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product1`.
    var product1: RswiftResources.ImageResource { .init(name: "product1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product10`.
    var product10: RswiftResources.ImageResource { .init(name: "product10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product11`.
    var product11: RswiftResources.ImageResource { .init(name: "product11", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product12`.
    var product12: RswiftResources.ImageResource { .init(name: "product12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product2`.
    var product2: RswiftResources.ImageResource { .init(name: "product2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product3`.
    var product3: RswiftResources.ImageResource { .init(name: "product3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product3_1`.
    var product3_1: RswiftResources.ImageResource { .init(name: "product3_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product3_2`.
    var product3_2: RswiftResources.ImageResource { .init(name: "product3_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product4`.
    var product4: RswiftResources.ImageResource { .init(name: "product4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product4_1`.
    var product4_1: RswiftResources.ImageResource { .init(name: "product4_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product4_2`.
    var product4_2: RswiftResources.ImageResource { .init(name: "product4_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product5`.
    var product5: RswiftResources.ImageResource { .init(name: "product5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product5_1`.
    var product5_1: RswiftResources.ImageResource { .init(name: "product5_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product6`.
    var product6: RswiftResources.ImageResource { .init(name: "product6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product6_1`.
    var product6_1: RswiftResources.ImageResource { .init(name: "product6_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product7`.
    var product7: RswiftResources.ImageResource { .init(name: "product7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product7_1`.
    var product7_1: RswiftResources.ImageResource { .init(name: "product7_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product8`.
    var product8: RswiftResources.ImageResource { .init(name: "product8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product8_1`.
    var product8_1: RswiftResources.ImageResource { .init(name: "product8_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product8_2`.
    var product8_2: RswiftResources.ImageResource { .init(name: "product8_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `product9`.
    var product9: RswiftResources.ImageResource { .init(name: "product9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `profileTabBarIcon`.
    var profileTabBarIcon: RswiftResources.ImageResource { .init(name: "profileTabBarIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `starIcon`.
    var starIcon: RswiftResources.ImageResource { .init(name: "starIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user1`.
    var user1: RswiftResources.ImageResource { .init(name: "user1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user2`.
    var user2: RswiftResources.ImageResource { .init(name: "user2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "gradient", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'gradient' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if UIKit.UIImage(named: "logo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }
  }
}